config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'comments/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[create new destroy]
      resources :likes, only: %i[create destroy]
    end
  end
  post 'users/:user_id/posts/post_:id/create_like', to: 'likes#create', as: 'like_create'
  get 'users/index'
  get 'users/show'
  get 'posts/index'
  get 'posts/show'
  root 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, param: :_user_id
  post 'api/login', to: 'authentication#login'
 
  namespace :api, defaults: { format: :json } do
      resources :users, only: %i[index show] do
        resources :posts, only: %i[index show] do
          resources :comments, only: %i[index show create]
        end
      end
    
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    # posts.includes(:author).order(created_at: :desc).limit(3)
    posts.order(created_at: :desc).first(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = User.all
    render json: @users, status: :ok
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @ind_user = User.find(params[:id])
    @current_user = current_user
  end
end

app/views/users/_showPosts.html.erb
<main  class="main-class">

<section class="section-class">
<article class="article-image">
<img src=<%= @ind_user.photo %> alt=<%= @ind_user.name %> >
</article>

<article class="names">
<%= @ind_user.name %>
<p> <small>Number of posts: <%= @ind_user.posts_counter %> </small> </p>
</article>
</section>

<section class="section-for-post">
<article class="bio-article bio-border">
<h5>Bio</h5>
<p><%= @ind_user.bio %></p>
</article>

<% if @ind_user.recent_posts.size.zero? %>
<div>
<p>No post to display at this time</p>
</div>
<% else %>
<% @ind_user.recent_posts.each do |post| %>

<section class="section-for-post">
<article class="bio-article2">

<h4>
<%= post.title %>
</h4>
<% if post.text.size > 100 %>
      <p><%= post.text[0, 100] %>...</p>
<% else %>
        <p><%= post.text %></p>
      <% end %>
<p class="small">
<small>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></small>
</p>
</article>
</section>

<% end %>
    <%= link_to "See all posts", user_posts_path(@ind_user)%>
<% end %>
<section>
<%= link_to 'Add post', new_user_post_path(current_user) %>
</main>

app/views/users/_user.html.erb
<main class="main-class">
    <% @users.each do |user|%>
<section class="section-class">
    <article class="article-image">
    <img src=<%= user.photo %> class="" alt=<%= user.name %>>
    </article>
    <article class="names">
    <%= link_to user.name, user %>
    <p> <small> Number of posts: <%= user.posts_counter %> </small> </p>
    </article>
</section>
    <% end %>
</main>

app/views/users/index.html.erb
<%= render "user" %>

app/views/users/show.html.erb
<%= render "showPosts" %>