config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'comments/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[create new destroy]
      resources :likes, only: %i[create destroy]
    end
  end
  post 'users/:user_id/posts/post_:id/create_like', to: 'likes#create', as: 'like_create'
  get 'users/index'
  get 'users/show'
  get 'posts/index'
  get 'posts/show'
  root 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, param: :_user_id
  post 'api/login', to: 'authentication#login'
 
  namespace :api, defaults: { format: :json } do
      resources :users, only: %i[index show] do
        resources :posts, only: %i[index show] do
          resources :comments, only: %i[index show create]
        end
      end
    
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_counter

  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end

  private

  def update_counter
    author.increment!(:posts_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authorize_request
  before_action :user

  def index
    @posts = Post.includes(:author).where(author: params[:user_id])
    render json: @posts
  end

  def show
    post = @user.posts.find_by_id!(params[:id])
    render json: post
  rescue ActiveRecord::RecordNotFound
    render json: { errors: 'Post not found' }, status: :not_found
  end

  private

  def user
    @user ||= User.find_by_id!(params[:user_id])
  rescue ActiveRecord::RecordNotFound
    render json: { errors: 'User not found' }, status: :not_found
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # load_and_authorize_resource
  # authorize_resource class: false

  def index
    @posts = Post.includes(:author).where(author: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    @current_user = current_user
    @ind_post = Post.includes(:author, comments: [:author]).find(params[:id])
  end

  def new
    @post = Post.new
    @current_user = current_user
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to user_posts_path(params[:user_id])
  end

  def create
    post = Post.new
    post.title = params[:user_posts][:title]
    post.text = params[:user_posts][:text]
    post.author = current_user

    respond_to do |format|
      format.html do
        if post.save
          flash[:success] = 'A post has been successfully created'
          redirect_to user_path(current_user)
        else
          flash.now[:error] = 'Post failed to be saved'
          render :new, new_user_post_path(current_user)
        end
      end
    end
  end
end

app/views/posts/_indPost.html.erb
<section class="main-class">
<div>
<div class="title-comment">
<h1>
<%= @ind_post.title  %>
</h1>
<p><small>Comments: <%= @ind_post.comments_counter %>, Likes: <%= @ind_post.likes_counter %></small>
</p>
</div>
    <p><%= @ind_post.text %></p>

<%= render "likes/button" %>

</div>
<div>
<% @ind_post.comments.each do |comment| %>
<%= comment.author.name %>: <%= comment.text %>

    <% if can? :manage, comment %>
    <%= link_to "Delete comment", user_post_comment_path(comment.author, comment.post, comment), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: "btn btn-danger btn-sm" %>
    
  <% end %>
<% end %>
</div>

<%= link_to 'Add Comment', new_user_post_comment_path(@current_user, @ind_post) %>
</section>

app/views/posts/_user.html.erb
<main class="main-class">
<section class="section-class">
      <article class="article-image">
      <img src=<%= @user.photo %> alt=<%= @user.name %>>
    </article>
        
        <article class="names">
          <h3><%= @user.name %></h3>
          <p><small>Number of posts: <%= @user.posts_counter %></small></p>
        </article>

</section>
        <% @posts.each do |post| %>
    <section class="section-for-post">
<article class="bio-article2">

      <h4><%= link_to post.title, user_post_path(current_user, post.id) %></h4>

              <% if can? :manage, post %>
  <%= link_to "Delete Post", user_post_path(current_user, post), data: {
                    turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %>
    <% end %>
      <% if post.text.size > 100 %>
      <p><%= post.text[0, 100] %>...</p>
<% else %>
        <p><%= post.text %></p>
      <% end %>
      <p class=small>
      <small>Comments:
      <%= post.comments_counter %> Likes: <%= post.likes_counter %></small></p>
      </article>

      <% if post.recent_comments.size.zero? %>
        <p><small>There are no comments yet</small></p>
      <% else %>
        <% post.recent_comments.each do |comment| %>
          <%= comment.author.name %>: <%= comment.text %><br/>
        <% end %>
        <% if post.comments_counter > 5 %>
          ...
        <% end %>
      <% end %>
     </section>
    <% end %>

</main>

app/views/posts/index.html.erb
<%= render "user" %>
    <%= link_to 'Add post', new_user_post_path(current_user) %>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path(@current_user), method: :post, local: true, scope: :user_posts do |form| %>
 
 <section class="app-form">
  <div>
    <%= form.text_field :title, placeholder: "Title" %>
  </div>

  <div>
    <%= form.text_field :text, placeholder: "Post text" %>
  </div>
<small>
  <%= form.submit %>
  </small>
 </section>
<% end %>

app/views/posts/show.html.erb
<%= render "indPost" %>